wandb_version: 1

lr:
  desc: null
  value: 0.0005
weight_decay:
  desc: null
  value: 0.04
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724934241.0
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 80
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 80
      3:
      - 2
      - 16
      - 23
      4: 3.12.4
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
